# Generated by Django 2.2.10 on 2020-04-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='building',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
