# Generated by Django 2.2.10 on 2020-10-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200502_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='asynchronous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
