# Generated by Django 2.2.6 on 2020-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20201026_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructional_method',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='asynchronous',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='honors',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='web',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
