# Generated by Django 2.2.6 on 2020-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20201026_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructional_method',
            field=models.CharField(blank=True, choices=[('F2F', 'Face to Face'), ('INTERN', 'Internship'), ('NOTRAD', 'Non-traditional'), ('WEB', 'Web Based'), ('ABROAD', 'Study abroad'), ('', ''), ('REMOTE', 'Remote Only'), ('F2FRO', 'F2F or Remote'), ('MIXED', 'Mixed, F2F and Remote')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='section',
            name='asynchronous',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='honors',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='web',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
