# Generated by Django 2.2.6 on 2020-10-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20201029_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructional_method',
            field=models.CharField(blank=True, choices=[('F2F', 'Face to Face'), ('INTERN', 'Internship'), ('NOTRAD', 'Non-traditional'), ('WEB', 'Web Based'), ('ABROAD', 'Study abroad'), ('', ''), ('REMOTE', 'Remote Only'), ('F2FRO', 'F2F or Remote'), ('MIXED', 'Mixed, F2F and Remote')], db_index=True, max_length=6),
        ),
    ]
