# Generated by Django 2.2.16 on 2020-11-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20201104_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='web',
            new_name='remote',
        ),
    ]
