# Generated by Django 2.2.16 on 2020-11-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20201104_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'terms',
            },
        ),
    ]
