# Generated by Django 2.2.17 on 2020-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20201111_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'terms',
            },
        ),
    ]
