# Generated by Django 2.2.6 on 2021-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='mcallen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
