# Generated by Django 2.2.24 on 2021-09-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210614_1411'),
        ('scraper', '0009_auto_20210801_1054'),
    ]

    operations = [
    ]
