# Generated by Django 2.2.6 on 2021-11-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_merge_20210912_1231'),
        ('scraper', '0009_section_mcallen'),
    ]

    operations = [
    ]
