declare namespace SectionSelectCssNamespace {
  export interface ISectionSelectCss {
    "add-bottom-space": string;
    addBottomSpace: string;
    "center-progress": string;
    centerProgress: string;
    "dense-list-item": string;
    denseListItem: string;
    "divider-container": string;
    dividerContainer: string;
    "dynamic-height-content": string;
    dynamicHeightContent: string;
    "error-text": string;
    errorText: string;
    "filter-option-table": string;
    filterOptionTable: string;
    "fit-content": string;
    fitContent: string;
    "indent-for-checkbox": string;
    indentForCheckbox: string;
    "less-checkbox-padding": string;
    lessCheckboxPadding: string;
    "list-subheader-content": string;
    "list-subheader-dense": string;
    listSubheaderContent: string;
    listSubheaderDense: string;
    "meeting-days": string;
    "meeting-info-wrapper": string;
    "meeting-time": string;
    "meeting-type": string;
    meetingDays: string;
    meetingInfoWrapper: string;
    meetingTime: string;
    meetingType: string;
    "my-icon-button": string;
    "my-list-item-icon": string;
    myIconButton: string;
    myListItemIcon: string;
    "name-honors-icon": string;
    nameHonorsIcon: string;
    "no-extra-space": string;
    "no-grades-available": string;
    "no-start-padding": string;
    noExtraSpace: string;
    noGradesAvailable: string;
    noStartPadding: string;
    "option-value-select": string;
    optionValueSelect: string;
    "placeholder-text": string;
    placeholderText: string;
    "prof-name-btn": string;
    profNameBtn: string;
    "remaining-seats": string;
    remainingSeats: string;
    "section-details-table": string;
    "section-header": string;
    "section-name-container": string;
    "section-num-and-icon": string;
    "section-rows": string;
    sectionDetailsTable: string;
    sectionHeader: string;
    sectionNameContainer: string;
    sectionNumAndIcon: string;
    sectionRows: string;
    "sections-wrapper": string;
    sectionsWrapper: string;
    "select-all-sort-by-container": string;
    "select-all-text": string;
    "select-menu": string;
    "select-root": string;
    selectAllSortByContainer: string;
    selectAllText: string;
    selectMenu: string;
    selectRoot: string;
    "sort-by-text": string;
    "sort-menu-position": string;
    "sort-order-button": string;
    "sort-order-button-icon": string;
    "sort-order-button-icon-ascending": string;
    "sort-type-menu-button": string;
    "sort-type-menu-button-icon": string;
    sortByText: string;
    sortMenuPosition: string;
    sortOrderButton: string;
    sortOrderButtonIcon: string;
    sortOrderButtonIconAscending: string;
    sortTypeMenuButton: string;
    sortTypeMenuButtonIcon: string;
    "static-height-content": string;
    staticHeightContent: string;
    "sub-title": string;
    subTitle: string;
    "table-container": string;
    tableContainer: string;
    warning: string;
  }
}

declare const SectionSelectCssModule: SectionSelectCssNamespace.ISectionSelectCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SectionSelectCssNamespace.ISectionSelectCss;
};

export = SectionSelectCssModule;
