export const container: string;
export const header: string;
export const headerTile: string;
export const calendarRow: string;
export const hourLabel: string;
export const hourMarker: string;
export const meetingsContainer: string;
export const calendarBody: string;
export const calendarDay: string;
