name: Danger
on: [pull_request]

jobs:
  danger:
    name: 'Danger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get node.js
        uses: actions/setup-node@v1

      - name: npm install danger
        run: npm install danger
        working-directory: ./autoscheduler/frontend/src

      - name: Danger
        run: npx danger ci
        working-directory: ./autoscheduler/frontend/src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}