name: Frontend CI
on:
  push:
    branches-ignore:
      - 'backend/**' # Don't run on any backend branches

jobs:
  test-frontend:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get node.js
        uses: actions/setup-node@v1

      - name: npm install
        run: npm install
        working-directory: ./autoscheduler/frontend/src

      - name: test
        run: npm test
        working-directory: ./autoscheduler/frontend/src

  build-frontend:
    name: 'Building'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get node.js
        uses: actions/setup-node@v1

      - name: npm install
        run: npm install
        working-directory: ./autoscheduler/frontend/src

      # Builds for production
      - name: build
        run: npm run build
        working-directory: ./autoscheduler/frontend/src

  lint-frontend:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get node.js
        uses: actions/setup-node@v1

      - name: npm install
        run: npm install
        working-directory: ./autoscheduler/frontend/src

      - name: lint
        run: npm run lint
        working-directory: ./autoscheduler/frontend/src
