name: Scrape Grades
on:
  schedule:
    # For pulling fall grades (usually released late December)
    - cron: '0 0 7 2 *'  # 2/7 at 00:00 every year
    - cron: '0 0 14 2 *' # 2/14 at 00:00 every year
    # For pulling spring grades (usually released late May)
    - cron: '0 0 7 6 *'  # 6/7 at 00:00 every year
    - cron: '0 0 14 6 *' # 6/14 at 00:00 every year
    # For pulling summer grades (usually released mid August)
    - cron: '0 0 7 10 *' # 10/7 at 00:00 every year
    - cron: '0 0 14 10 *' # 10/14 at 00:00 every year

jobs:
  scrape-grades:
    name: 'Scrape Grades'
    runs-on: ubuntu-latest
    env:
      GCP_DB_NAME: ${{ secrets.GCP_DB_NAME }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_SCRAPE_CHANNEL_ID: ${{ secrets.DISCORD_SCRAPE_CHANNEL_ID }}
      DISCORD_FEEDBACK_CHANNEL_ID: ${{ secrets.DISCORD_FEEDBACK_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@master

      - name: Fill in Postgres credentials
        run: bash fill_credentials.sh ${{ secrets.POSTGRES_USER }} ${{ secrets.POSTGRES_PASS }}

      - name: Fill in Discord credentials
        run: bash fill_discord_credentials.sh ${{ secrets.DISCORD_BOT_TOKEN }} ${{ secrets.DISCORD_SCRAPE_CHANNEL_ID }} ${{ secrets.DISCORD_FEEDBACK_CHANNEL_ID }}

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_config_path: ./autoscheduler/app.yaml

      - name: Initialize GCP Credentials
        run: |
          # This client-secret.json is converted by GCP_SA_KEY
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # By default it copies to ./client-secret.json, but we need it in docker/cloud-sql-proxy so its in
      # the cloud-sql-proxy-cred-file's context
      - name: Copy client-secret.json
        run: cp client-secret.json docker/cloud-sql-proxy-cred-file/client-secret.json

      - name: docker-build
        # sudo -E so we can access the GCP_DB_NAME env var 
        run: sudo -E docker-compose up --abort-on-container-exit scrape-grades
